base: &base
  adapter: mysql
  host: 127.0.0.1
  username: root
  password: astb612

development:
  database: radiant_pkg_development
  <<: *base

test:
  database: radiant_pkg_test
  <<: *base

production:
  database: radiant_pkg_production
  <<: *base